"""
模块名:   mainUI
功能：    定义了mainUI类，用于绘制 UI 界面
"""
#导入相关包
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication,QStyleFactory

#定义类：mainUI
class mainUI(object):
    #界面初始化函数
    def setupUi(self, mainUI):
        #设置主窗口大小、标题、风格等
        mainUI.setObjectName("mainUI")
        mainUI.setFixedSize(1600, 900)
        mainUI.setWindowTitle('八数码实验')
        mainUI.setWindowIcon(QtGui.QIcon('resource/8.ico'))
        QApplication.setStyle(QStyleFactory.create("Fusion"))
        
        """
        设置弹出输入框和对话框
        """
        #弹出输入框
        self.inputDialog=QtWidgets.QInputDialog()
        #弹出对话框
        self.dialog=QtWidgets.QWidget()
        self.dialog.setFixedSize(400, 200)
        self.dialog.setWindowModality(Qt.ApplicationModal)
        self.dialog.setWindowFlags(Qt.FramelessWindowHint)
        self.dialog.setObjectName("dialog") 
        self.dialog.setStyleSheet("#dialog{background-color: #6495ED}")
        self.dialog.setWindowOpacity(0.8)
        self.label_run=QtWidgets.QLabel(self.dialog) 
        #设置字体
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(24)
        #弹出对话框中得文字和按钮
        self.label_run.setGeometry(QtCore.QRect(50, 20, 300, 100))
        self.label_run.setFont(font)
        self.label_run.setAlignment(QtCore.Qt.AlignCenter)
        self.label_run.setText("运 * 行 * 中")
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.btn=QtWidgets.QPushButton(self.dialog)
        self.btn.setGeometry(QtCore.QRect(150, 130, 100, 50))
        self.btn.setFont(font)
        self.btn.setText("  继  续  ")
        self.btn.setEnabled(False)
        
        """
        绘制初始状态、目标状态、动态演示的九宫格表示
        """
        initx=100
        inity=100
        goalx=450
        goaly=100
        showx=450
        showy=480
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.initText = QtWidgets.QLabel(mainUI)
        self.initText.setGeometry(QtCore.QRect(135, 45, 300, 30))
        self.initText.setFont(font)
        self.initText.setText("初 * 始 * 状 * 态")
        self.goalText = QtWidgets.QLabel(mainUI)
        self.goalText.setGeometry(QtCore.QRect(485, 45, 300, 30))
        self.goalText.setFont(font)
        self.goalText.setText("目 * 标 * 状 * 态")
        self.menuText = QtWidgets.QLabel(mainUI)
        self.menuText.setGeometry(QtCore.QRect(135, 430, 300, 30))
        self.menuText.setFont(font)
        self.menuText.setText("功 * 能 * 菜 * 单")
        self.showText = QtWidgets.QLabel(mainUI)
        self.showText.setGeometry(QtCore.QRect(485, 430, 300, 30))
        self.showText.setFont(font)
        self.showText.setText("步 * 骤 * 演 * 示")
        self.init1 = QtWidgets.QLabel(mainUI)
        self.init1.setGeometry(QtCore.QRect(initx, inity, 100, 100))
        self.init1.setPixmap(QtGui.QPixmap('resource/1.ico'))     
        self.init1.setObjectName("init1")   
        self.init2 = QtWidgets.QLabel(mainUI)
        self.init2.setGeometry(QtCore.QRect(initx+100, inity, 100, 100))
        self.init2.setPixmap(QtGui.QPixmap('resource/2.ico'))     
        self.init2.setObjectName("init2")    
        self.init3 = QtWidgets.QLabel(mainUI)
        self.init3.setGeometry(QtCore.QRect(initx+200, inity, 100, 100))
        self.init3.setPixmap(QtGui.QPixmap('resource/3.ico'))     
        self.init3.setObjectName("init3")        
        self.init4 = QtWidgets.QLabel(mainUI)
        self.init4.setGeometry(QtCore.QRect(initx, inity+100, 100, 100))
        self.init4.setPixmap(QtGui.QPixmap('resource/4.ico'))     
        self.init4.setObjectName("init4")        
        self.init5 = QtWidgets.QLabel(mainUI)
        self.init5.setGeometry(QtCore.QRect(initx+100, inity+100, 100, 100))
        self.init5.setPixmap(QtGui.QPixmap('resource/5.ico'))     
        self.init5.setObjectName("init5")    
        self.init6 = QtWidgets.QLabel(mainUI)
        self.init6.setGeometry(QtCore.QRect(initx+200, inity+100, 100, 100))
        self.init6.setPixmap(QtGui.QPixmap('resource/6.ico'))     
        self.init6.setObjectName("init6")        
        self.init7 = QtWidgets.QLabel(mainUI)
        self.init7.setGeometry(QtCore.QRect(initx, inity+200, 100, 100))
        self.init7.setPixmap(QtGui.QPixmap('resource/7.ico'))     
        self.init7.setObjectName("init7")        
        self.init8 = QtWidgets.QLabel(mainUI)
        self.init8.setGeometry(QtCore.QRect(initx+100, inity+200, 100, 100))
        self.init8.setPixmap(QtGui.QPixmap('resource/8.ico'))     
        self.init8.setObjectName("init8")    
        self.init9 = QtWidgets.QLabel(mainUI)
        self.init9.setGeometry(QtCore.QRect(initx+200, inity+200, 100, 100))
        self.init9.setPixmap(QtGui.QPixmap('resource/0.ico'))     
        self.init9.setObjectName("init9")               
        self.goal1 = QtWidgets.QLabel(mainUI)
        self.goal1.setGeometry(QtCore.QRect(goalx, goaly, 100, 100))
        self.goal1.setPixmap(QtGui.QPixmap('resource/1.ico'))     
        self.goal1.setObjectName("goal1")   
        self.goal2 = QtWidgets.QLabel(mainUI)
        self.goal2.setGeometry(QtCore.QRect(goalx+100, goaly, 100, 100))
        self.goal2.setPixmap(QtGui.QPixmap('resource/2.ico'))     
        self.goal2.setObjectName("goal2")    
        self.goal3 = QtWidgets.QLabel(mainUI)
        self.goal3.setGeometry(QtCore.QRect(goalx+200, goaly, 100, 100))
        self.goal3.setPixmap(QtGui.QPixmap('resource/3.ico'))     
        self.goal3.setObjectName("goal3")        
        self.goal4 = QtWidgets.QLabel(mainUI)
        self.goal4.setGeometry(QtCore.QRect(goalx, goaly+100, 100, 100))
        self.goal4.setPixmap(QtGui.QPixmap('resource/4.ico'))     
        self.goal4.setObjectName("goal4")        
        self.goal5 = QtWidgets.QLabel(mainUI)
        self.goal5.setGeometry(QtCore.QRect(goalx+100, goaly+100, 100, 100))
        self.goal5.setPixmap(QtGui.QPixmap('resource/5.ico'))     
        self.goal5.setObjectName("goal5")    
        self.goal6 = QtWidgets.QLabel(mainUI)
        self.goal6.setGeometry(QtCore.QRect(goalx+200, goaly+100, 100, 100))
        self.goal6.setPixmap(QtGui.QPixmap('resource/6.ico'))     
        self.goal6.setObjectName("goal6")        
        self.goal7 = QtWidgets.QLabel(mainUI)
        self.goal7.setGeometry(QtCore.QRect(goalx, goaly+200, 100, 100))
        self.goal7.setPixmap(QtGui.QPixmap('resource/7.ico'))     
        self.goal7.setObjectName("goal7")        
        self.goal8 = QtWidgets.QLabel(mainUI)
        self.goal8.setGeometry(QtCore.QRect(goalx+100, goaly+200, 100, 100))
        self.goal8.setPixmap(QtGui.QPixmap('resource/8.ico'))     
        self.goal8.setObjectName("goal8")    
        self.goal9 = QtWidgets.QLabel(mainUI)
        self.goal9.setGeometry(QtCore.QRect(goalx+200, goaly+200, 100, 100))
        self.goal9.setPixmap(QtGui.QPixmap('resource/0.ico'))     
        self.goal9.setObjectName("goal9")          
        self.show1 = QtWidgets.QLabel(mainUI)
        self.show1.setGeometry(QtCore.QRect(showx, showy, 100, 100))
        self.show1.setPixmap(QtGui.QPixmap('resource/1.ico'))     
        self.show1.setObjectName("show1")
        self.show2 = QtWidgets.QLabel(mainUI)
        self.show2.setGeometry(QtCore.QRect(showx+100, showy, 100, 100))
        self.show2.setPixmap(QtGui.QPixmap('resource/2.ico'))     
        self.show2.setObjectName("show2")
        self.show3 = QtWidgets.QLabel(mainUI)
        self.show3.setGeometry(QtCore.QRect(showx+200, showy, 100, 100))
        self.show3.setPixmap(QtGui.QPixmap('resource/3.ico'))     
        self.show3.setObjectName("show3")
        self.show4 = QtWidgets.QLabel(mainUI)
        self.show4.setGeometry(QtCore.QRect(showx, showy+100, 100, 100))
        self.show4.setPixmap(QtGui.QPixmap('resource/4.ico'))     
        self.show4.setObjectName("show4")
        self.show5 = QtWidgets.QLabel(mainUI)
        self.show5.setGeometry(QtCore.QRect(showx+100, showy+100, 100, 100))
        self.show5.setPixmap(QtGui.QPixmap('resource/5.ico'))     
        self.show5.setObjectName("show5")
        self.show6 = QtWidgets.QLabel(mainUI)
        self.show6.setGeometry(QtCore.QRect(showx+200, showy+100, 100, 100))
        self.show6.setPixmap(QtGui.QPixmap('resource/6.ico'))     
        self.show6.setObjectName("show6")
        self.show7 = QtWidgets.QLabel(mainUI)
        self.show7.setGeometry(QtCore.QRect(showx, showy+200, 100, 100))
        self.show7.setPixmap(QtGui.QPixmap('resource/7.ico'))     
        self.show7.setObjectName("show7")
        self.show8 = QtWidgets.QLabel(mainUI)
        self.show8.setGeometry(QtCore.QRect(showx+100, showy+200, 100, 100))
        self.show8.setPixmap(QtGui.QPixmap('resource/8.ico'))     
        self.show8.setObjectName("show8")
        self.show9= QtWidgets.QLabel(mainUI)
        self.show9.setGeometry(QtCore.QRect(showx+200, showy+200, 100, 100))
        self.show9.setPixmap(QtGui.QPixmap('resource/0.ico'))     
        self.show9.setObjectName("show9")
        self.init1.setScaledContents(True)
        self.init2.setScaledContents(True)
        self.init3.setScaledContents(True)
        self.init4.setScaledContents(True)
        self.init5.setScaledContents(True)
        self.init6.setScaledContents(True)
        self.init7.setScaledContents(True)
        self.init8.setScaledContents(True)
        self.init9.setScaledContents(True)
        self.goal1.setScaledContents(True)
        self.goal2.setScaledContents(True)
        self.goal3.setScaledContents(True)
        self.goal4.setScaledContents(True)
        self.goal5.setScaledContents(True)
        self.goal6.setScaledContents(True)
        self.goal7.setScaledContents(True)
        self.goal8.setScaledContents(True)
        self.goal9.setScaledContents(True)
        self.show1.setScaledContents(True)
        self.show2.setScaledContents(True)
        self.show3.setScaledContents(True)
        self.show4.setScaledContents(True)
        self.show5.setScaledContents(True)
        self.show6.setScaledContents(True)
        self.show7.setScaledContents(True)
        self.show8.setScaledContents(True)
        self.show9.setScaledContents(True)
        
        """
        功能菜单设计
        """
        #修改状态
        self.setStateButton=QtWidgets.QPushButton(mainUI)
        self.setStateButton.setGeometry(QtCore.QRect(100, 490, 150, 40))
        self.setStateButton.setCheckable(True)
        self.setStateButton.setText("设置初始状态")
        self.setStateButton.setToolTip("使用键盘“w，s，a，d”移动")
        self.setStateButton.setObjectName("stbtn")      
        self.inputStateButton=QtWidgets.QPushButton(mainUI)
        self.inputStateButton.setGeometry(QtCore.QRect(270, 490, 150, 40))
        self.inputStateButton.setText("输入初始/目标状态")
        self.inputStateButton.setObjectName("stbtn")
        #选择算法
        self.label_a = QtWidgets.QLabel(mainUI)
        font = QtGui.QFont()
        font.setFamily("Geeza Pro")
        font.setPointSize(10)
        self.label_a.setFont(font)
        self.label_a.setGeometry(QtCore.QRect(100, 540, 75, 40))
        self.label_a.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a.setText("选择算法:")
        self.label_a.setObjectName("label_a")       
        self.optAlgorithm = QtWidgets.QComboBox(mainUI)
        self.optAlgorithm.setGeometry(QtCore.QRect(175, 540, 75, 40))
        self.optAlgorithm.addItem("A1")
        self.optAlgorithm.addItem("A2")
        self.optAlgorithm.addItem("A3")
        self.optAlgorithm.addItem("A4")
        self.optAlgorithm.addItem("A5")
        self.optAlgorithm.addItem("A6")
        self.optAlgorithm.addItem("A7")
        self.optAlgorithm.setObjectName("optAlgorithm") 
        
        #分步演示
        self.stepCheckBox=QtWidgets.QCheckBox(mainUI)
        self.stepCheckBox.setGeometry(QtCore.QRect(270, 540, 150, 40))
        self.stepCheckBox.setFont(font)
        self.stepCheckBox.setText(" 开启分步演示")
        self.stepCheckBox.setObjectName("stepCheckBox")
        
        #开始和重置按钮
        self.Run = QtWidgets.QPushButton(mainUI)
        self.Run.setGeometry(QtCore.QRect(100, 590, 150, 40))
        self.Run.setText("开  始")
        self.Run.setObjectName("Run")
        self.Reset = QtWidgets.QPushButton(mainUI)
        self.Reset.setGeometry(QtCore.QRect(270, 590, 150, 40))
        self.Reset.setText("重  置")
        self.Reset.setObjectName("Reset")        

        #上一步和下一步按钮
        self.lastButton = QtWidgets.QPushButton(mainUI)
        self.lastButton.setGeometry(QtCore.QRect(100, 640, 150, 40))
        self.lastButton.setText("上一步")
        self.lastButton.setObjectName("nextButton")   
        self.nextButton = QtWidgets.QPushButton(mainUI)
        self.nextButton.setGeometry(QtCore.QRect(270, 640, 150, 40))
        self.nextButton.setText("下一步")
        self.nextButton.setObjectName("nextButton")   
        
        #搜索结果展示
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_1 = QtWidgets.QLabel(mainUI)
        self.label_1.setFont(font)
        self.label_1.setGeometry(QtCore.QRect(100,690,150,20))
        self.label_1.setText("解步长:")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(mainUI)
        self.label_2.setFont(font)
        self.label_2.setGeometry(QtCore.QRect(270,690,150,20))
        self.label_2.setText("当前步数:")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(mainUI)
        self.label_9.setFont(font)
        self.label_9.setGeometry(QtCore.QRect(360,710,10,20))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")        
        self.label_3 = QtWidgets.QLabel(mainUI)
        self.label_3.setFont(font)
        self.label_3.setGeometry(QtCore.QRect(100,710,250,20))
        self.label_3.setText("运行时间:")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(mainUI)
        self.label_4.setFont(font)
        self.label_4.setGeometry(QtCore.QRect(100,730,300,20))
        self.label_4.setText("生成结点数:")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(mainUI)
        self.label_5.setFont(font)
        self.label_5.setGeometry(QtCore.QRect(100,750,300,20))
        self.label_5.setText("扩展结点数:")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(mainUI)
        self.label_6.setFont(font)
        self.label_6.setGeometry(QtCore.QRect(100,770,300,20))
        self.label_6.setText("未扩展结点数:")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(mainUI)
        self.label_7.setFont(font)
        self.label_7.setGeometry(QtCore.QRect(100,790,300,20))
        self.label_7.setText("外显率:")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(mainUI)
        self.label_8.setFont(font)
        self.label_8.setGeometry(QtCore.QRect(100,810,300,20))
        self.label_8.setText("有效支因子:")
        self.label_8.setObjectName("label_8")
        
        #将信号与槽连接
        QtCore.QMetaObject.connectSlotsByName(mainUI)
        
